### ISSUE TITLE
Ability to hide time bar for some zone

### ISSUE THREAD

**Issue by ddff7** [davidefu/warp#1]
In some case there is no need to have the time bar for a zone during booking.
So I'm going to plan a specific settings in the zone to hide it

**Comment by ddff7** [comment]
#5 merged in v0.3

**Comment by konraaaaad** [comment]
@davidefu or anybody able to provide some help...

Can I just add `showTimeSlide = False` as an additional line to the config.py or how would I go about hiding the time bar?

Probably stupid question, but a bit of a beginner here...

**Comment by ddff7** [comment]
@konraaaaad when you create the zone in the UI, simply do not flag "Show time" in italian "Mostra tempo" (as you can see from the screenshot)

![Image](https://github.com/user-attachments/assets/c2fe5b6d-22d3-4994-a36b-10812c534a62)

in this way you can have some zones that are showing time and some other not
